# Generated by Django 2.0.13 on 2019-05-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibroModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('edicion', models.IntegerField()),
                ('copias', models.IntegerField()),
            ],
        ),
    ]
